version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    volumes:
    - db-volume:/var/lib/postgresql/data

  api:
    image: rozaworks/user-account-api
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"
volumes:
  db-volume:
  h2-data: