version: '3'

services:
  database_stage:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    volumes:
    - db-volume:/var/lib/postgresql/data

  api_stage:
    image: rozaworks/user-account-api
    environment:
      DB_HOST: database_stage
    ports:
      - "9292:9090"
volumes:
  db-volume: